field: 017df12e-c23a-4778-a575-be6bc8e30d28
fieldLayouts:
  2edb4239-bb47-452e-8e33-5d181d96c7a3:
    tabs:
      -
        elements:
          -
            fieldUid: 88a6d1e8-c5c4-4974-b873-3b7fb1108f0f
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f1cb158f-117d-49bf-9452-f4aa62d6bfa6
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8c3cddd6-b342-4594-9537-9f4409b09801
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c0450952-c18b-4888-8559-f503f6ecda60
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  88a6d1e8-c5c4-4974-b873-3b7fb1108f0f:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c3cddd6-b342-4594-9537-9f4409b09801:
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: ''
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c0450952-c18b-4888-8559-f503f6ecda60:
    contentColumnType: text
    fieldGroup: null
    handle: tagline
    instructions: ''
    name: Tagline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f1cb158f-117d-49bf-9452-f4aa62d6bfa6:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:57f475e0-d66e-4374-826f-d20f4c2e0392'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:57f475e0-d66e-4374-826f-d20f4c2e0392'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:57f475e0-d66e-4374-826f-d20f4c2e0392'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: inhoud
name: Inhoud
sortOrder: 1
