field: 69c8fef7-9f3c-4904-a863-7f1faae79456
fieldLayouts:
  b2b1ab77-15a1-4eae-bdd3-c0345092f7ea:
    tabs:
      -
        elements:
          -
            fieldUid: 2dddf412-5161-44c5-8745-ea2daad97ad5
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0985f336-930a-4cbe-9bc9-1a5b2dc98bfa
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 857fe406-0c3a-4a12-ac1c-31a252701c9c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6178007b-4c62-4fc0-bac8-c94a5ca6054a
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0985f336-930a-4cbe-9bc9-1a5b2dc98bfa:
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: ''
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2dddf412-5161-44c5-8745-ea2daad97ad5:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6178007b-4c62-4fc0-bac8-c94a5ca6054a:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:57f475e0-d66e-4374-826f-d20f4c2e0392'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:57f475e0-d66e-4374-826f-d20f4c2e0392'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:57f475e0-d66e-4374-826f-d20f4c2e0392'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  857fe406-0c3a-4a12-ac1c-31a252701c9c:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: inhoud
name: Inhoud
sortOrder: 1
