handle: topNavigation
instructions: ''
maxNodes: '3'
name: 'Top navigation'
permissions:
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: ''
propagateNodes: false
siteSettings:
  495739ba-ab45-4dd5-bb2a-7c6a82b657f4: null
sortOrder: 1
structure:
  maxLevels: '1'
  uid: 56edd0f3-6e60-44ad-9869-ba2de2b97615
