columnSuffix: null
contentColumnType: string
fieldGroup: 5e4913d6-ed0e-48fc-a49b-593cc43d370a
handle: about
instructions: ''
name: About
searchable: false
settings:
  contentTable: '{{%matrixcontent_about}}'
  maxBlocks: '3'
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
