contentColumnType: string
fieldGroup: f57375eb-70ec-48b9-be73-fd19ecf64112
handle: email
instructions: ''
name: email
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
