contentColumnType: text
fieldGroup: f57375eb-70ec-48b9-be73-fd19ecf64112
handle: phone
instructions: ''
name: phone
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
