columnSuffix: null
contentColumnType: string
fieldGroup: 5e4913d6-ed0e-48fc-a49b-593cc43d370a
handle: slider
instructions: ''
name: Slider
searchable: false
settings:
  contentTable: '{{%matrixcontent_slider}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
