columnSuffix: null
contentColumnType: string
fieldGroup: 5e4913d6-ed0e-48fc-a49b-593cc43d370a
handle: video
instructions: ''
name: Video
searchable: false
settings:
  contentTable: '{{%matrixcontent_video}}'
  maxBlocks: '3'
  minBlocks: '0'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
