dateModified: 1656411460
email:
  fromEmail: jan@inteiro.be
  fromName: 'N2 Buiten Leven'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0fa59c62-07f8-4803-9bb6-6eb234e621cc: Footer # Footer
    1bbab94c-f7e3-4b59-ac73-00eb765dcd39: 'Youtube Link' # Youtube Link
    1cded62c-10ee-440d-b58d-ab59124e729c: Video # Video
    1ee2b958-a93e-4003-828e-7693fec1ea06: Contact # Contact
    2f812ee4-1836-46d3-a361-c406fd315a66: Beschrijving # Beschrijving
    3ed12512-3cfb-4053-bc2f-e39a07c300e1: Inhoud # Inhoud
    3fb792c3-ecee-40e3-9f37-98f779fc4275: Image # Image
    5ed33758-cc2d-4198-90f9-217e910afb50: Inhoud # Inhoud
    6b35b821-027c-4f37-9b02-ab413c779b50: 'Buiten leven' # Buiten leven
    6bb59240-5314-420b-9313-22f3bb99258b: Button # Button
    7d393000-5764-45ee-8ef8-8a763d3b13f7: Description # Description
    7f1aa322-426e-4ae7-8c6e-eb34d739df74: Subtitel # Subtitel
    9ae6a83f-50e9-4229-92ab-8345d7daf54a: Feature # Feature
    9b564739-6899-41bd-a1b6-8957971599cb: Image # Image
    9cad2396-e443-4c72-88ef-bb40523864f5: slide # slide
    9de6491f-6e9a-406e-8040-285511749958: Afbeelding # Afbeelding
    9fa5e361-1bfd-4714-be76-0a9469e26258: Subtitle # Subtitle
    30cd21bc-6de2-4e3a-ad4c-37b12bc984ef: 'Hoofd navigatie' # Hoofd navigatie
    031f9d3a-0ebd-4464-90c8-181518a0a676: Video # Video
    38eca1b1-4d57-449a-8e19-f30b2549f551: Titel # Titel
    40eadc69-aa11-4eaa-bbae-01bf6ecc0572: Description # Description
    58c21f9e-ea4f-4540-b8e5-eb16cc1782a0: Pagetitle # Pagetitle
    068b7a2f-47d8-43f5-9096-416deb09344f: Zonwering # Zonwering
    93faf1a7-15c2-4426-8ef6-a8228690fe70: Subheading # Subheading
    308eaded-c544-4be8-9917-816799645d84: 'Knop 2' # Knop 2
    340e0520-333d-41b3-9fd3-854bb4e955f4: 'Ramen en deuren' # Ramen en deuren
    654d17cd-1701-4fdf-b7c0-38696d55e9c7: Button # Button
    993ce49d-45ac-4bbc-8c2e-e8d18201c18b: Inhoud # Inhoud
    6350fd46-75ed-4c68-87f4-59c4d59225f6: Contact # Contact
    8112ebe6-f1a8-41a9-a6c2-f2d410ebed8f: 'Knop 1' # Knop 1
    9403ae2f-7a0b-4674-8dde-53f6b27ff353: Slider # Slider
    20111be7-987a-4364-bf9a-90f35d955762: About # About
    39859fa6-1365-422e-a85f-6dc12cc05548: 'Afbeelding 2' # Afbeelding 2
    495739ba-ab45-4dd5-bb2a-7c6a82b657f4: 'N2 Buitenleven' # N2 Buitenleven
    1952691a-e332-4ff1-9c5f-d1943ce38caf: Heading # Heading
    39477821-209b-40f3-8421-e884d055f66c: Features # Features
    46684890-a6fd-476a-a2f7-7626c39c7216: 'Over N²' # Over N²
    a72ae909-9c61-4feb-be30-078b6b81e687: USP # USP
    b42a32aa-b28d-449b-8b86-c6faf7be3c8e: subTitle # subTitle
    bb7afd91-77b7-4de6-a50a-bbfafd78ecd5: Zonwering # Zonwering
    bbd5ba34-7a22-478b-b5ad-ee41644e6970: 'Afbeelding 1' # Afbeelding 1
    bdded17f-fb36-4be6-815b-f8fafdfe1fd9: Header # Header
    d9e3dc57-f8a5-427c-8e75-7a95f82a19d9: Heading # Heading
    d27b6565-c579-447b-bf09-cad8b3e7457c: Contactinfo # Contactinfo
    dee29ced-14aa-48b7-8add-5b871c620f2d: Description # Description
    e304dd92-2441-4b42-bd28-7c7388d59106: Heading # Heading
    f5d52687-9762-4528-8789-1d5a02cf4e99: Linkedin # Linkedin
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'Namens Tom van N2'
      prependSubject: 'New message from N2 Buiten Leven'
      successFlashMessage: 'Jouw bericht is verstuurd.'
      toEmail: $CONTACT_FORM_EMAIL
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      honeypotParam: buitenpot\
  cookie-consent-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      allow: 'Allow cookies'
      async_js: '1'
      auto_inject: '1'
      decline: Decline
      defer_js: '1'
      disable_in_live_preview: ''
      dismiss: 'Got it!'
      dismiss_on_scroll: '0'
      dismiss_on_timeout: '0'
      excluded_categories: null
      excluded_entry_types: null
      expiry_days: '365'
      honour_do_not_track_header: ''
      layout: block
      learn: 'Learn More'
      learn_more_link: 'http://cookiesandyou.com/'
      message: 'This website uses cookies to ensure you get the best experience on our website.'
      palette: default
      palette_banner: '#000000'
      palette_banner_text: '#ffffff'
      palette_button: '#f1d600'
      palette_button_text: '#000000'
      palette_left_button_bg: '#f8e71c'
      palette_left_button_text: '#000000'
      palette_link: '#ffffff'
      position: bottom
      preload_css: '1'
      revokable: ''
      secure_only: ''
      target: _blank
      type: info
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 905MIQ77HD1XYWOFAEARGTH3
    schemaVersion: 1.0.21
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
system:
  edition: solo
  live: true
  name: 'N2 Buitenleven'
  retryDuration: null
  schemaVersion: 3.7.33
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
