dateModified: 1637938392
email:
  fromEmail: jan@inteiro.be
  fromName: 'N2 Buiten Leven'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0fa59c62-07f8-4803-9bb6-6eb234e621cc: Footer # Footer
    1ee2b958-a93e-4003-828e-7693fec1ea06: Contact # Contact
    3fb792c3-ecee-40e3-9f37-98f779fc4275: Image # Image
    5ed33758-cc2d-4198-90f9-217e910afb50: Inhoud # Inhoud
    6b35b821-027c-4f37-9b02-ab413c779b50: 'Buiten leven' # Buiten leven
    58c21f9e-ea4f-4540-b8e5-eb16cc1782a0: Pagetitle # Pagetitle
    93faf1a7-15c2-4426-8ef6-a8228690fe70: Subheading # Subheading
    993ce49d-45ac-4bbc-8c2e-e8d18201c18b: Inhoud # Inhoud
    6350fd46-75ed-4c68-87f4-59c4d59225f6: Contact # Contact
    172278cf-6f59-450f-8cf7-09fda3eba0f0: 'Sociale media' # Sociale media
    1952691a-e332-4ff1-9c5f-d1943ce38caf: Heading # Heading
    46684890-a6fd-476a-a2f7-7626c39c7216: 'Over N²' # Over N²
    d27b6565-c579-447b-bf09-cad8b3e7457c: Contactinfo # Contactinfo
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'Namens Tom van N2'
      prependSubject: 'New message from N2 Buiten Leven'
      successFlashMessage: 'Jouw bericht is verstuurd.'
      toEmail: $CONTACT_FORM_EMAIL
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      honeypotParam: buitenpot\
  cookie-consent-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      allow: 'Allow cookies'
      async_js: '1'
      auto_inject: '1'
      decline: Decline
      defer_js: '1'
      disable_in_live_preview: ''
      dismiss: 'Got it!'
      dismiss_on_scroll: '0'
      dismiss_on_timeout: '0'
      excluded_categories: null
      excluded_entry_types: null
      expiry_days: '365'
      honour_do_not_track_header: ''
      layout: block
      learn: 'Learn More'
      learn_more_link: 'http://cookiesandyou.com/'
      message: 'This website uses cookies to ensure you get the best experience on our website.'
      palette: default
      palette_banner: '#000000'
      palette_banner_text: '#ffffff'
      palette_button: '#f1d600'
      palette_button_text: '#000000'
      palette_left_button_bg: '#f8e71c'
      palette_left_button_text: '#000000'
      palette_link: '#ffffff'
      position: bottom
      preload_css: '1'
      revokable: ''
      secure_only: ''
      target: _blank
      type: info
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 905MIQ77HD1XYWOFAEARGTH3
    schemaVersion: 1.0.21
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
system:
  edition: solo
  live: true
  name: 'N2 Buiten Leven'
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
