fieldLayouts:
  49c7d44f-b636-45dd-ac6a-e1d111a749cf:
    tabs:
      -
        elements:
          -
            fieldUid: 0abcb6d7-20a6-4595-a22a-44c543c17dc5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b9961e3-bfd7-4170-8555-243a0a32e175
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 97d89cea-3acf-4486-98f7-f71af5e4da6c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 11a60bb9-1be0-40d6-bf1e-86fb680c9fef
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: footer
name: Footer
sortOrder: 2
