fieldLayouts:
  5a1ba532-adda-474d-b575-3f252050d6db:
    tabs:
      -
        elements:
          -
            fieldUid: 0760cfef-5910-490a-80e4-094dd8c40d18
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a440f858-deda-4867-8f20-4d5bb49af636
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: socialmedia
name: 'Sociale media'
sortOrder: 3
