enableVersioning: true
handle: about
name: 'Over N²'
propagationMethod: all
siteSettings:
  495739ba-ab45-4dd5-bb2a-7c6a82b657f4: # N2 Buitenleven
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: over-n2-buiten-leven
type: single
