enableVersioning: true
handle: buitenLeven
name: 'Buiten leven'
propagationMethod: all
siteSettings:
  495739ba-ab45-4dd5-bb2a-7c6a82b657f4: # N2 Buitenleven
    enabledByDefault: true
    hasUrls: true
    template: category
    uriFormat: poolhouse-buiten-leven
type: single
