defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  495739ba-ab45-4dd5-bb2a-7c6a82b657f4: # N2 Buitenleven
    enabledByDefault: true
    hasUrls: true
    template: contact/_index
    uriFormat: contact
type: single
