defaultPlacement: end
enableVersioning: true
handle: poorten
name: Poorten
propagationMethod: all
siteSettings:
  495739ba-ab45-4dd5-bb2a-7c6a82b657f4: # N2 Buitenleven
    enabledByDefault: true
    hasUrls: true
    template: poorten/_entry
    uriFormat: poorten
type: single
